import React, { useState } from "react";

export default function ShareCenter({ currentPlan }) {
  const [copied, setCopied] = useState(false);
  const [isVisible, setIsVisible] = useState(false);

  if (!currentPlan) return null;

  const { feasibility, summary, ai, map: mapData } = currentPlan;
  const poiName = ai?.title || mapData?.selectedPoi?.name || "Layover Stay";

  const getShareText = () => {
    return `✈️ My Layover Plan: ${poiName}\n` +
           `Risk: ${feasibility.riskLabel}\n` +
           `Feasibility Score: ${feasibility.score}/100\n` +
           `Layover Time: ${summary.layoverMinutes} min\n` +
           `Generated by LayoverPlus`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(getShareText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy", err);
    }
  };

  return (
    <div className="share-center">
      <button 
        type="button" 
        className="secondary-action share-trigger" 
        onClick={() => setIsVisible(!isVisible)}
      >
        {isVisible ? "Hide Share Options" : "📤 Share Plan"}
      </button>

      {isVisible && (
        <div className="share-card card reveal">
          <h3>Share your itinerary</h3>
          <p className="mini-label">Preview</p>
          <pre className="share-preview">
            {getShareText()}
          </pre>
          <div className="share-actions">
            <button type="button" className="preset-btn" onClick={handleCopy}>
              {copied ? "✅ Copied!" : "📋 Copy to Clipboard"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
